### ISSUE TITLE
Closure detected instead of method  

### ISSUE THREAD

**Issue by ThePixelDeveloper** [Halleck45/PhpMetrics#72]
```
➜  web git:(master) phpmetrics . --report-html ../html
PHPMetrics by Jean-François Lépine <https://twitter.com/Halleck45>

  139/1295 [===>------------------------]  10%
  149/1295 [===>------------------------]  11%
  151/1295 [===>------------------------]  11%
  200/1295 [====>-----------------------]  15%

                                      
  [Exception]                         
  Closure detected instead of method  
```

Got this exception when trying to test it on a project. The current PHP version I'm running is ...

```
➜  web git:(master) php --version
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

Although the project targets a lower PHP version than 5.4

Help appreciated.

**Comment by hugofonseca** [comment]
Maybe this related https://github.com/Halleck45/PhpMetrics/issues/33 ?

**Comment by Halleck45** [comment]
> Maybe this is related #33 ?

Maybe. I've added verbosity in this error with [this commit](https://github.com/Halleck45/PhpMetrics/commit/f351a97b102dc7b4e868a34a5cf934b2da31006d)

@ThePixelDeveloper, can you retry with the [latest phar](https://github.com/Halleck45/PhpMetrics/blob/master/build/phpmetrics.phar) please ?

**Comment by ThePixelDeveloper** [comment]
Tried again and got the following

```
[Exception]
  a 'Exception' exception occured analyzing file ./mailchimp/MCAPI.class.php
  Message: Closure detected instead of method
  Details:
  ------------
  Stack:
  #0 phar:///usr/local/bin/phpmetrics/src/Hal/Component/OOP/Extractor/Extractor.php(127): Hal\Component\OOP\Extractor\MethodExtractor->extract(4805, Object(Hal\Compon
  ent\Token\TokenCollection))
  #1 phar:///usr/local/bin/phpmetrics/src/Hal/Application/Command/Job/Analyze/FileAnalyzer.php(138): Hal\Component\OOP\Extractor\Extractor->extract('./html/sites/al..
  .')
  #2 phar:///usr/local/bin/phpmetrics/src/Hal/Application/Command/Job/DoAnalyze.php(121): Hal\Application\Command\Job\Analyze\FileAnalyzer->execute('./html/sites/al..
  .')
  #3 phar:///usr/local/bin/phpmetrics/src/Hal/Application/Command/Job/Queue.php(51): Hal\Application\Command\Job\DoAnalyze->execute(Object(Hal\Component\Result\Result
  Collection), Object(Hal\Component\Result\ResultCollection))
  #4 phar:///usr/local/bin/phpmetrics/src/Hal/Application/Command/RunMetricsCommand.php(119): Hal\Application\Command\Job\Queue->execute(Object(Hal\Component\Result\R
  esultCollection), Object(Hal\Component\Result\ResultCollection))
  #5 phar:///usr/local/bin/phpmetrics/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Hal\Application\Command\RunMetricsCommand->execute(Ob
  ject(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #6 phar:///usr/local/bin/phpmetrics/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Sym
  fony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #7 phar:///usr/local/bin/phpmetrics/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Objec
  t(Hal\Application\Command\RunMetricsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #8 phar:///usr/local/bin/phpmetrics/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfo
  ny\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  #9 /usr/local/bin/phpmetrics(17): Symfony\Component\Console\Application->run()
  #10 {main}
  ------------
  Do not hesitate to report a bug: https://github.com/Halleck45/PhpMetrics/issues
```

**Comment by fonsecas72** [comment]
> Although the project targets a lower PHP version than 5.4

Can you tell what's the exact PHP version?

**Comment by Halleck45** [comment]
`MCAPI.class.php` is a very old file. PhpMetrics probably cannot support this file. I'll try to fix that.

I found the file [here](https://apidocs.mailchimp.com/api/downloads/#php), but what's the version of your file ? Can you create a gist with the content of your `MCAPI.class.php` file ?

**Comment by Halleck45** [comment]
No update since 6 month, I close this issue
